// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RRF.RRFDbContext;

namespace RRF.RRFDbContext.Migrations
{
    [DbContext(typeof(RRFDbContext))]
    [Migration("20190512080130_Initial role config")]
    partial class Initialroleconfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "5ef2fca0-238d-4f9a-bcb6-d8657264e785",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "1ddcd1c9-feeb-406e-8bf7-25a0f9e436f3",
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("RoleId");

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.HasKey("Id", "RoleId");

                    b.ToTable("IdentityRoleChain");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<int>("Id");

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.HasKey("UserId", "Id");

                    b.ToTable("IdentityUserClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("RoleId");

                    b.Property<string>("UserId");

                    b.HasKey("RoleId", "UserId");

                    b.HasAlternateKey("UserId", "RoleId");

                    b.ToTable("IdentityUserRole");
                });

            modelBuilder.Entity("RRF.EFModels.Client", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("APIKey");

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = "baa0d4c2-1589-4378-be1c-238612953ae1",
                            APIKey = new Guid("00000000-0000-0000-0000-000000000000"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7b5f5cde-8785-45a0-aab0-fa67b7f33096",
                            Email = "client@mail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLIENT@MAIL.COM",
                            NormalizedUserName = "CLIENT@MAIL.COM",
                            PhoneNumber = "+359359",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "66fba0e5-0967-406c-9fed-d86483cff10a",
                            TwoFactorEnabled = false,
                            UserName = "Client"
                        },
                        new
                        {
                            Id = "e3a958db-ec09-4afd-87c1-1197fec81617",
                            APIKey = new Guid("00000000-0000-0000-0000-000000000000"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1814e1b2-9321-4476-92f2-54a86f296128",
                            Email = "admin@mail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MAIL.COM",
                            NormalizedUserName = "ADMIN@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFleHp6vKM9aWJhpAoH84r0l20KCvOYw7G5csKXrK6wWoFF3ikR6lne9XukxUkF+2g==",
                            PhoneNumber = "+359359",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "8b96073c-378f-4c68-8d40-4e0abd74df18",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("RRF.EFModels.DescendingElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name");

                    b.Property<int?>("RssSettingDescendantElement_Id");

                    b.HasKey("Id");

                    b.HasIndex("RssSettingDescendantElement_Id")
                        .IsUnique()
                        .HasFilter("[RssSettingDescendantElement_Id] IS NOT NULL");

                    b.ToTable("DescendingElements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2019, 5, 12, 11, 1, 28, 119, DateTimeKind.Local).AddTicks(1693),
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2019, 5, 12, 11, 1, 28, 119, DateTimeKind.Local).AddTicks(3178),
                            Name = "item",
                            RssSettingDescendantElement_Id = 1
                        });
                });

            modelBuilder.Entity("RRF.EFModels.ImageElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("ElementSubName");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name");

                    b.Property<int?>("RssSettingImageFormatElement_Id");

                    b.HasKey("Id");

                    b.HasIndex("RssSettingImageFormatElement_Id");

                    b.ToTable("ImageElements");
                });

            modelBuilder.Entity("RRF.EFModels.ModelElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ImageSRC");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LinkToCurrentElement");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("PubDate");

                    b.Property<int>("RssSettingDisplayModelElementId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("RssSettingDisplayModelElementId")
                        .IsUnique();

                    b.ToTable("ModelElements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2019, 5, 12, 11, 1, 28, 120, DateTimeKind.Local).AddTicks(8666),
                            Description = "description",
                            ImageSRC = "image",
                            IsDeleted = false,
                            LinkToCurrentElement = "link",
                            ModifiedOn = new DateTime(2019, 5, 12, 11, 1, 28, 121, DateTimeKind.Local).AddTicks(268),
                            PubDate = "pubDate",
                            RssSettingDisplayModelElementId = 1,
                            Title = "title"
                        });
                });

            modelBuilder.Entity("RRF.EFModels.RssChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientId");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("RssChannels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = "baa0d4c2-1589-4378-be1c-238612953ae1",
                            CreatedOn = new DateTime(2019, 5, 12, 11, 1, 28, 85, DateTimeKind.Local).AddTicks(8780),
                            IsDeleted = false,
                            Name = "testRssChannel",
                            URL = "https://www.vesti.bg/rss.php"
                        });
                });

            modelBuilder.Entity("RRF.EFModels.RssSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientId");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<int?>("RssChanel_Id");

                    b.HasKey("Id");

                    b.HasIndex("RssChanel_Id")
                        .IsUnique()
                        .HasFilter("[RssChanel_Id] IS NOT NULL");

                    b.ToTable("RssSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = "baa0d4c2-1589-4378-be1c-238612953ae1",
                            CreatedOn = new DateTime(2019, 5, 12, 11, 1, 28, 118, DateTimeKind.Local).AddTicks(6072),
                            IsDeleted = false,
                            RssChanel_Id = 1
                        });
                });

            modelBuilder.Entity("RRF.EFModels.XElementModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name");

                    b.Property<int?>("RssSettingFormatElements_Id");

                    b.Property<string>("UseName");

                    b.HasKey("Id");

                    b.HasIndex("RssSettingFormatElements_Id");

                    b.ToTable("XElementsModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "<p>",
                            RssSettingFormatElements_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "</p>",
                            RssSettingFormatElements_Id = 1
                        });
                });

            modelBuilder.Entity("RRF.EFModels.DescendingElement", b =>
                {
                    b.HasOne("RRF.EFModels.RssSetting", "RssSettingDescendantElement")
                        .WithOne("DescendantElement")
                        .HasForeignKey("RRF.EFModels.DescendingElement", "RssSettingDescendantElement_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RRF.EFModels.ImageElement", b =>
                {
                    b.HasOne("RRF.EFModels.RssSetting", "RssSettingImageFormatElement")
                        .WithMany("RssImageFormatElements")
                        .HasForeignKey("RssSettingImageFormatElement_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RRF.EFModels.ModelElement", b =>
                {
                    b.HasOne("RRF.EFModels.RssSetting", "RssSettingDisplayModelElement")
                        .WithOne("RssModelElements")
                        .HasForeignKey("RRF.EFModels.ModelElement", "RssSettingDisplayModelElementId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RRF.EFModels.RssChannel", b =>
                {
                    b.HasOne("RRF.EFModels.Client", "Client")
                        .WithMany("Channels")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("RRF.EFModels.RssSetting", b =>
                {
                    b.HasOne("RRF.EFModels.RssChannel", "RssChannel")
                        .WithOne("RssSeting")
                        .HasForeignKey("RRF.EFModels.RssSetting", "RssChanel_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RRF.EFModels.XElementModel", b =>
                {
                    b.HasOne("RRF.EFModels.RssSetting", "RssSettingFormatElements")
                        .WithMany("RssFormatElements")
                        .HasForeignKey("RssSettingFormatElements_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
